require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlarmHistoriesController do

  # This should return the minimal set of attributes required to create a valid
  # AlarmHistory. As you add validations to AlarmHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "arduino_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlarmHistoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all alarm_histories as @alarm_histories" do
      alarm_history = AlarmHistory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:alarm_histories).should eq([alarm_history])
    end
  end

  describe "GET show" do
    it "assigns the requested alarm_history as @alarm_history" do
      alarm_history = AlarmHistory.create! valid_attributes
      get :show, {:id => alarm_history.to_param}, valid_session
      assigns(:alarm_history).should eq(alarm_history)
    end
  end

  describe "GET new" do
    it "assigns a new alarm_history as @alarm_history" do
      get :new, {}, valid_session
      assigns(:alarm_history).should be_a_new(AlarmHistory)
    end
  end

  describe "GET edit" do
    it "assigns the requested alarm_history as @alarm_history" do
      alarm_history = AlarmHistory.create! valid_attributes
      get :edit, {:id => alarm_history.to_param}, valid_session
      assigns(:alarm_history).should eq(alarm_history)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlarmHistory" do
        expect {
          post :create, {:alarm_history => valid_attributes}, valid_session
        }.to change(AlarmHistory, :count).by(1)
      end

      it "assigns a newly created alarm_history as @alarm_history" do
        post :create, {:alarm_history => valid_attributes}, valid_session
        assigns(:alarm_history).should be_a(AlarmHistory)
        assigns(:alarm_history).should be_persisted
      end

      it "redirects to the created alarm_history" do
        post :create, {:alarm_history => valid_attributes}, valid_session
        response.should redirect_to(AlarmHistory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alarm_history as @alarm_history" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmHistory.any_instance.stub(:save).and_return(false)
        post :create, {:alarm_history => { "arduino_id" => "invalid value" }}, valid_session
        assigns(:alarm_history).should be_a_new(AlarmHistory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmHistory.any_instance.stub(:save).and_return(false)
        post :create, {:alarm_history => { "arduino_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alarm_history" do
        alarm_history = AlarmHistory.create! valid_attributes
        # Assuming there are no other alarm_histories in the database, this
        # specifies that the AlarmHistory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlarmHistory.any_instance.should_receive(:update_attributes).with({ "arduino_id" => "MyString" })
        put :update, {:id => alarm_history.to_param, :alarm_history => { "arduino_id" => "MyString" }}, valid_session
      end

      it "assigns the requested alarm_history as @alarm_history" do
        alarm_history = AlarmHistory.create! valid_attributes
        put :update, {:id => alarm_history.to_param, :alarm_history => valid_attributes}, valid_session
        assigns(:alarm_history).should eq(alarm_history)
      end

      it "redirects to the alarm_history" do
        alarm_history = AlarmHistory.create! valid_attributes
        put :update, {:id => alarm_history.to_param, :alarm_history => valid_attributes}, valid_session
        response.should redirect_to(alarm_history)
      end
    end

    describe "with invalid params" do
      it "assigns the alarm_history as @alarm_history" do
        alarm_history = AlarmHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => alarm_history.to_param, :alarm_history => { "arduino_id" => "invalid value" }}, valid_session
        assigns(:alarm_history).should eq(alarm_history)
      end

      it "re-renders the 'edit' template" do
        alarm_history = AlarmHistory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmHistory.any_instance.stub(:save).and_return(false)
        put :update, {:id => alarm_history.to_param, :alarm_history => { "arduino_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alarm_history" do
      alarm_history = AlarmHistory.create! valid_attributes
      expect {
        delete :destroy, {:id => alarm_history.to_param}, valid_session
      }.to change(AlarmHistory, :count).by(-1)
    end

    it "redirects to the alarm_histories list" do
      alarm_history = AlarmHistory.create! valid_attributes
      delete :destroy, {:id => alarm_history.to_param}, valid_session
      response.should redirect_to(alarm_histories_url)
    end
  end

end
