require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TodoTasksController do

  # This should return the minimal set of attributes required to create a valid
  # TodoTask. As you add validations to TodoTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "reef_tank_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TodoTasksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all todo_tasks as @todo_tasks" do
      todo_task = TodoTask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:todo_tasks).should eq([todo_task])
    end
  end

  describe "GET show" do
    it "assigns the requested todo_task as @todo_task" do
      todo_task = TodoTask.create! valid_attributes
      get :show, {:id => todo_task.to_param}, valid_session
      assigns(:todo_task).should eq(todo_task)
    end
  end

  describe "GET new" do
    it "assigns a new todo_task as @todo_task" do
      get :new, {}, valid_session
      assigns(:todo_task).should be_a_new(TodoTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested todo_task as @todo_task" do
      todo_task = TodoTask.create! valid_attributes
      get :edit, {:id => todo_task.to_param}, valid_session
      assigns(:todo_task).should eq(todo_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TodoTask" do
        expect {
          post :create, {:todo_task => valid_attributes}, valid_session
        }.to change(TodoTask, :count).by(1)
      end

      it "assigns a newly created todo_task as @todo_task" do
        post :create, {:todo_task => valid_attributes}, valid_session
        assigns(:todo_task).should be_a(TodoTask)
        assigns(:todo_task).should be_persisted
      end

      it "redirects to the created todo_task" do
        post :create, {:todo_task => valid_attributes}, valid_session
        response.should redirect_to(TodoTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved todo_task as @todo_task" do
        # Trigger the behavior that occurs when invalid params are submitted
        TodoTask.any_instance.stub(:save).and_return(false)
        post :create, {:todo_task => { "reef_tank_id" => "invalid value" }}, valid_session
        assigns(:todo_task).should be_a_new(TodoTask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TodoTask.any_instance.stub(:save).and_return(false)
        post :create, {:todo_task => { "reef_tank_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested todo_task" do
        todo_task = TodoTask.create! valid_attributes
        # Assuming there are no other todo_tasks in the database, this
        # specifies that the TodoTask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TodoTask.any_instance.should_receive(:update_attributes).with({ "reef_tank_id" => "1" })
        put :update, {:id => todo_task.to_param, :todo_task => { "reef_tank_id" => "1" }}, valid_session
      end

      it "assigns the requested todo_task as @todo_task" do
        todo_task = TodoTask.create! valid_attributes
        put :update, {:id => todo_task.to_param, :todo_task => valid_attributes}, valid_session
        assigns(:todo_task).should eq(todo_task)
      end

      it "redirects to the todo_task" do
        todo_task = TodoTask.create! valid_attributes
        put :update, {:id => todo_task.to_param, :todo_task => valid_attributes}, valid_session
        response.should redirect_to(todo_task)
      end
    end

    describe "with invalid params" do
      it "assigns the todo_task as @todo_task" do
        todo_task = TodoTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TodoTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => todo_task.to_param, :todo_task => { "reef_tank_id" => "invalid value" }}, valid_session
        assigns(:todo_task).should eq(todo_task)
      end

      it "re-renders the 'edit' template" do
        todo_task = TodoTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TodoTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => todo_task.to_param, :todo_task => { "reef_tank_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested todo_task" do
      todo_task = TodoTask.create! valid_attributes
      expect {
        delete :destroy, {:id => todo_task.to_param}, valid_session
      }.to change(TodoTask, :count).by(-1)
    end

    it "redirects to the todo_tasks list" do
      todo_task = TodoTask.create! valid_attributes
      delete :destroy, {:id => todo_task.to_param}, valid_session
      response.should redirect_to(todo_tasks_url)
    end
  end

end
