require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UpdateCodesController do

  # This should return the minimal set of attributes required to create a valid
  # UpdateCode. As you add validations to UpdateCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "reef_tank_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UpdateCodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all update_codes as @update_codes" do
      update_code = UpdateCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:update_codes).should eq([update_code])
    end
  end

  describe "GET show" do
    it "assigns the requested update_code as @update_code" do
      update_code = UpdateCode.create! valid_attributes
      get :show, {:id => update_code.to_param}, valid_session
      assigns(:update_code).should eq(update_code)
    end
  end

  describe "GET new" do
    it "assigns a new update_code as @update_code" do
      get :new, {}, valid_session
      assigns(:update_code).should be_a_new(UpdateCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested update_code as @update_code" do
      update_code = UpdateCode.create! valid_attributes
      get :edit, {:id => update_code.to_param}, valid_session
      assigns(:update_code).should eq(update_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UpdateCode" do
        expect {
          post :create, {:update_code => valid_attributes}, valid_session
        }.to change(UpdateCode, :count).by(1)
      end

      it "assigns a newly created update_code as @update_code" do
        post :create, {:update_code => valid_attributes}, valid_session
        assigns(:update_code).should be_a(UpdateCode)
        assigns(:update_code).should be_persisted
      end

      it "redirects to the created update_code" do
        post :create, {:update_code => valid_attributes}, valid_session
        response.should redirect_to(UpdateCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved update_code as @update_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        UpdateCode.any_instance.stub(:save).and_return(false)
        post :create, {:update_code => { "reef_tank_id" => "invalid value" }}, valid_session
        assigns(:update_code).should be_a_new(UpdateCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UpdateCode.any_instance.stub(:save).and_return(false)
        post :create, {:update_code => { "reef_tank_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested update_code" do
        update_code = UpdateCode.create! valid_attributes
        # Assuming there are no other update_codes in the database, this
        # specifies that the UpdateCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UpdateCode.any_instance.should_receive(:update_attributes).with({ "reef_tank_id" => "1" })
        put :update, {:id => update_code.to_param, :update_code => { "reef_tank_id" => "1" }}, valid_session
      end

      it "assigns the requested update_code as @update_code" do
        update_code = UpdateCode.create! valid_attributes
        put :update, {:id => update_code.to_param, :update_code => valid_attributes}, valid_session
        assigns(:update_code).should eq(update_code)
      end

      it "redirects to the update_code" do
        update_code = UpdateCode.create! valid_attributes
        put :update, {:id => update_code.to_param, :update_code => valid_attributes}, valid_session
        response.should redirect_to(update_code)
      end
    end

    describe "with invalid params" do
      it "assigns the update_code as @update_code" do
        update_code = UpdateCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UpdateCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => update_code.to_param, :update_code => { "reef_tank_id" => "invalid value" }}, valid_session
        assigns(:update_code).should eq(update_code)
      end

      it "re-renders the 'edit' template" do
        update_code = UpdateCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UpdateCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => update_code.to_param, :update_code => { "reef_tank_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested update_code" do
      update_code = UpdateCode.create! valid_attributes
      expect {
        delete :destroy, {:id => update_code.to_param}, valid_session
      }.to change(UpdateCode, :count).by(-1)
    end

    it "redirects to the update_codes list" do
      update_code = UpdateCode.create! valid_attributes
      delete :destroy, {:id => update_code.to_param}, valid_session
      response.should redirect_to(update_codes_url)
    end
  end

end
